# Aprendiendo a usar numpy

## Fundamendos de numpy

In [1]:
import numpy as np

### Creación de arreglos y matrices

#### Arreglos unidimensionales

In [2]:
L = [1, 2, 3]
A = np.array(L)

print(L)
print(A)

[1, 2, 3]
[1 2 3]


#### Arreglos multidimensionales

In [3]:
L2 = [[1, 2], [3, 4]]
A2 = np.array(L2)

print(L2)
print(A2)

[[1, 2], [3, 4]]
[[1 2]
 [3 4]]


#### Arreglos de unos y ceros

In [4]:
ceros = np.zeros((2, 3))
unos = np.ones((3, 2))

print(ceros)
print(unos)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


#### Arreglos de rango

In [9]:
rango = np.arange(10)
lp = np.linspace(0, 1, 5)
print(rango)
print(lp)

[0 1 2 3 4 5 6 7 8 9]
[0.   0.25 0.5  0.75 1.  ]


#### Arreglo o atriz de identidad

In [8]:
identidad = np.eye(3)
print(identidad)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


para especificar el tipo de dato del array, podemos colocar un atributo en la funcion llamado **dtype**

### Indexacion y selección de arrays

#### Acceder a arrays unidimensionales

In [24]:
a = np.array([1, 2, 3, 4, 5])
print(a[2])
print(a[::2])

3
[1 3 5]


#### Acceder a arrays multidimensionales

In [22]:
b = np.array([
    [1, 2, 3, 4, 5, 6], 
    [7, 8, 9, 10, 11, 12], 
    [13, 14, 15, 16, 17, 18]
])

print(b[-1, -1])
print(b[:2, :2])

18
[[1 2]
 [7 8]]


#### Acceder a varios elementos a traves de un array de indices

In [25]:
e = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
indices = np.array([1, 4, 4, 2])
e[indices]

array([2, 5, 5, 3])

#### Acceder a elementos de array mediante condiciones

In [31]:
f = np.array([1, -1, 3, -5, 2, 4, -7, -9])
condicion = f>0

print(f)
print(condicion)
print(f[condicion])
print(f[f>1])

[ 1 -1  3 -5  2  4 -7 -9]
[ True False  True False  True  True False False]
[1 3 2 4]
[3 2 4]


### Operaciones básicas de arrays

#### Operaciones entre arrays

In [36]:
a = np.array([1, 2, 3])
b = np.array([4, 1, 6])

print(a+b)
print(a-b)
print(a*b)
print(b/a)

[5 3 9]
[-3  1 -3]
[ 4  2 18]
[4.  0.5 2. ]


#### Operaciones entre array y escalar

In [40]:
print(a+10)
print(a-2)
print(a*10)
print(b/10)

[11 12 13]
[-1  0  1]
[10 20 30]
[0.4 0.1 0.6]


## Operaciones avanzadas de numpy

### Broadcasting

El broadcasting es el operar matrices que no tienen las mismas dimensiones. 

Consiste en que si tenemos dos matrices de distintos tamaños, la de menor 
tamaño se extenderá al tamaño de la mayor en un eje compatible. 

- **Concepto clave**:
  - Solo se puede usar broadcasting si amboas array tienen las mismas dimensiones, o una de ellas es 1

Para usar broadcasting tenemos una reglas:

- **Regla 1**: Si los arrays no tienen las misma dimensiones, se añade una dimension de tamaño 1 al inicio del array con menos dimensiones
- **Regla 2**: Se comparan las dimensiones de los arrays. Si ambos tienen las mismas dimensiones o una de ellas es 1, se puede operar, sino se obtiene un error
- **Regla3**: Los arrays con dimensiones de tamaño 1 se expanden para coincidir con el tamaño de la dimension mayor

In [44]:
a = np.array([
    [7, 8, 9],
    [4, 5, 6],
    [1, 2, 3] 
])

b = np.array([
    [1], 
    [2],
    [3]
])

print(a)
print(b)
print(a*b)

[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[1]
 [2]
 [3]]
[[ 7  8  9]
 [ 8 10 12]
 [ 3  6  9]]


### Funciones universales

#### Funciones de suma, resta, multiplicacion y division

In [50]:
a = np.array([1, 2, 3])
b = np.array([3, 2, 1])

print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))

[4 4 4]
[-2  0  2]
[3 4 3]
[0.33333333 1.         3.        ]


#### Trabajar con angulos, y funciones trigonometricas

In [52]:
angulos = np.array([0, 30, 60, 90])
angulos_rad = np.radians(angulos)

print(np.sin(angulos))

print(np.sin(angulos_rad))
print(np.cos(angulos_rad))
print(np.tan(angulos_rad))

[ 0.         -0.98803162 -0.30481062  0.89399666]
[0.        0.5       0.8660254 1.       ]
[1.00000000e+00 8.66025404e-01 5.00000000e-01 6.12323400e-17]
[0.00000000e+00 5.77350269e-01 1.73205081e+00 1.63312394e+16]


#### Funciones de comparación

In [57]:
print(a, b)

print(np.less(a, b))
print(np.equal(a, b))
print(np.greater(a, b))

[1 2 3] [3 2 1]
[ True False False]
[False  True False]
[False False  True]


#### Funcion para elevar a una potencia

In [58]:
print(np.power(a, b))

[1 4 3]


#### Funcion para desviación y de promedio

In [60]:
print(np.mean(a))
print(np.std(b))

2.0
0.816496580927726


## Algebra lineal con numpy

### Manipulación y reducción de arrays

#### Copiar un array por referencia y por valor

In [61]:
x = np.array([1, 2, 3])
y = x
z = x.copy()

x[1] = 9

print(x)
print(y)
print(z)

[1 9 3]
[1 9 3]
[1 2 3]


#### Redibujar array como trigonometricas, y aplanar matriz a una dimension

In [63]:
a = np.arange(1, 10)
b = a.reshape((3, 3))
c = b.flatten() # es una copia
d = b.ravel()   # es un apuntador

print(a)
print(b)
print(c)
print(d)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


#### Funciones aplicadas a filas y columnas

In [69]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.min(m, axis=1) # min, max, sum, std, mean

array([1, 4, 7])

### Operaciones de algebra lineal

In [71]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 2], [2, 3]])

c = np.dot(a, b)
d = a @ b

print(c)
print(d)

[[ 5  8]
 [11 18]]
[[ 5  8]
 [11 18]]
